apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtq-grafana
  labels:
    app: dtq-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtq-grafana
  template:
    metadata:
      labels:
        app: dtq-grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.1.4
          imagePullPolicy: IfNotPresent
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
              subPath: datasource.yaml
            - name: grafana-dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              subPath: dashboards.yaml
            - name: grafana-dashboard-overview
              mountPath: /var/lib/grafana/dashboards/dtq-overview.json
              subPath: dtq-overview.json
      volumes:
        - name: grafana-datasources
          configMap:
            name: dtq-grafana-datasources
        - name: grafana-dashboard-provider
          configMap:
            name: dtq-grafana-dashboard-provider
        - name: grafana-dashboard-overview
          configMap:
            name: dtq-grafana-dashboard-overview
