apiVersion: v1
kind: ConfigMap
metadata:
  name: dtq-grafana-datasources
  labels:
    app: dtq-grafana
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: DTQ Prometheus
        uid: dtq-prometheus
        type: prometheus
        access: proxy
        url: http://dtq-prometheus.dtq-monitoring.svc.cluster.local:9090
        isDefault: true
        editable: false
