apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dtq-monitoring

resources:
  - namespace.yaml
  - prometheus-configmap.yaml
  - prometheus-rules-configmap.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - grafana-datasources-configmap.yaml
  - grafana-dashboard-provider-configmap.yaml
  - grafana-dashboard-dtq-overview-configmap.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
