apiVersion: v1
kind: ConfigMap
metadata:
  name: dtq-prometheus-config
  labels:
    app: dtq-prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "dtq-api"
        metrics_path: /metrics
        static_configs:
          - targets: ["dtq-api.dtq.svc.cluster.local:80"]

      - job_name: "dtq-worker"
        metrics_path: /metrics
        static_configs:
          - targets: ["dtq-worker-metrics.dtq.svc.cluster.local:2112"]
