apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dtq

resources:
  - namespace.yaml
  - api-configmap.yaml
  - worker-configmap.yaml
  - runtime-secrets.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
  - worker-service.yaml
  - ui-deployment.yaml
  - ui-service.yaml

images:
  - name: dtq-api
    newName: dtq-api
    newTag: latest
  - name: dtq-worker
    newName: dtq-worker
    newTag: latest
  - name: dtq-ui
    newName: dtq-ui
    newTag: latest
