apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtq-worker
  labels:
    app: dtq-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dtq-worker
  template:
    metadata:
      labels:
        app: dtq-worker
    spec:
      containers:
        - name: worker
          image: dtq-worker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: WORKER_GRPC_ADDR
              value: ":9090"
